Create a 5x5 matrix, A, with entries randomly chosen integers between 0 and 9. To generate the
random matrix, set the random seed as the last two digits of your roll number. Reduce matrix A to its
Row Echelon Form by performing elementary row operations.

In [6]:
import numpy as np

seed = 10  
np.random.seed(seed)


A = np.random.randint(0, 10, (5, 5))


print("Original Matrix A:")
print(A)
print()

A = A.astype(float)
for i in range(5):
    # Find the first nonzero entry in the current row
    pivot = np.argmax(A[i] != 0)
    if pivot == len(A):  # Skip if row is all zeros
        continue

    
    A[[i, pivot]] = A[[pivot, i]]
    A[i] /= A[i, i]

    for k in range(i + 1, 5):
        A[k] -= A[k, i] * A[i]


print("Row Echelon Form of Matrix A:")
print(A)

Original Matrix A:
[[9 4 0 1 9]
 [0 1 8 9 0]
 [8 6 4 3 0]
 [4 6 8 1 8]
 [4 1 3 6 5]]

Row Echelon Form of Matrix A:
[[ 1.          0.44444444  0.          0.11111111  1.        ]
 [ 0.          1.          8.          9.          0.        ]
 [-0.         -0.          1.          1.27857143  0.51428571]
 [-0.         -0.         -0.          1.         -3.84713376]
 [-0.         -0.         -0.         -0.          1.        ]]
