Perform Singular Value Decomposition on the matrix A obtained in Question 2. Separate and print
matrices U, Σ, and 𝑉் . Verify that A equals the product of U, Σ, and 𝑉் . Additionally, find the rank 2
and rank 3 approximations of matrix A.

In [2]:
import numpy as np

# Define the matrix A
np.random.seed(10)
A = np.random.randint(0, 10, (5, 5))

# Perform Singular Value Decomposition (SVD)
U, S, Vt = np.linalg.svd(A, full_matrices=False)

# Create the diagonal matrix Σ from the singular values
Sigma = np.diag(S)

# Print the matrices U, Σ, and V^T
print("Matrix U:")
print(U)
print("\nMatrix Σ:")
print(Sigma)
print("\nMatrix V^T:")
print(Vt)
print()

# Verify that A equals the product of U, Σ, and V^T
reconstructed_A = np.dot(U, np.dot(Sigma, Vt))
print("Is A equal to U * Σ * V^T?", np.allclose(A, reconstructed_A))
print()

# Find the rank 2 and rank 3 approximations of matrix A
rank_2_approx = np.dot(U[:, :2], np.dot(np.diag(S[:2]), Vt[:2, :]))
rank_3_approx = np.dot(U[:, :3], np.dot(np.diag(S[:3]), Vt[:3, :]))

print("Rank 2 Approximation of A:")
print(rank_2_approx)
print("\nRank 3 Approximation of A:")
print(rank_3_approx)

Matrix U:
[[-0.50607307  0.57352192  0.02218552  0.39771732 -0.50625231]
 [-0.31917458 -0.80609058  0.03688056  0.15189298 -0.47319542]
 [-0.42724355 -0.01415109 -0.84662405 -0.27476083  0.15810408]
 [-0.56116957  0.04548564  0.51352228 -0.63267664  0.13796702]
 [-0.3802227  -0.13791804  0.13292933  0.58564171  0.68975568]]

Matrix Σ:
[[22.05964437  0.          0.          0.          0.        ]
 [ 0.         12.12231444  0.          0.          0.        ]
 [ 0.          0.          6.81340664  0.          0.        ]
 [ 0.          0.          0.          6.16417546  0.        ]
 [ 0.          0.          0.          0.          0.04487528]]

Matrix V^T:
[[-0.5321108  -0.3923077  -0.44843858 -0.34011794 -0.49616066]
 [ 0.38596251  0.12688059 -0.54075466 -0.61916965  0.39893308]
 [-0.5852456  -0.25538746  0.20775431 -0.12837386  0.72981034]
 [ 0.19357487 -0.50553734 -0.51724476  0.61997672  0.23462202]
 [ 0.43348286 -0.71358617  0.44247401 -0.3163823  -0.08370411]]

Is A equal to U *